mydata <- fread(input="household_power_consumption.txt", header=TRUE, stringsAsFactors=FALSE, na.strings="?")
data <- mydata[mydata$Date %in% c("1/2/2007","2/2/2007"),]

gapdata <- as.numeric(data$Global_active_power)
datedata <- strptime(paste(data$Date, data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
sub1data <- as.numeric(data$Sub_metering_1)
sub2data <- as.numeric(data$Sub_metering_2)
sub3data <- as.numeric(data$Sub_metering_3)
voltagedata <- as.numeric(data$Voltage)
grpdata <- as.numeric(data$Global_reactive_power)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(datedata, gapdata, xlab="", ylab="Global Active Power", cex=0.25)
plot(datedata, voltagedata, xlab="datetime", ylab="Voltage", cex=0.25)
plot(datedata, sub1data, type="l", xlab="", ylab="Enery sub metering",cex=0.25)
lines(datedata, sub2data, type="l", xlab="", col="red",cex=0.25)
lines(datedata, sub3data, type="l", xlab="", col="blue",cex=0.25)
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"), lwd=1.0)
plot(datedata, grpdata, xlab="datetime", ylab="Global_reactive_power", cex=0.25)
dev.off()
